# 各模块的开关
ModuleSwitch:
  # B站动态订阅
  BiliSubscription: false
  # 切噜语翻译
  Cheru: false
  # 奇怪的娱乐功能 (随机禁言啥的)
  HaveFun: true
  # 随机色图
  Hso: false
  # 公会排名查询
  PcrGuildRank: false

# 随机色图设置
HsoConfig:
  # 色图源 Local/Lolicon/Yukari/自定义服务器
  Source: Local
  # 是否检查源证书
  CheckSSLCert: false
  # Pximg代理服务器地址，如果没有设置为null即可
  PximgProxy: null
  # 是否使用本地缓存
  UseCache: false
  # 是否使用XML格式发送图片（装逼大图）
  # 有被风控风险谨慎启用
  # 此功能只能在Go上使用
  CardImage: false
  # 色图缓存文件夹的大小限制(MB)
  SizeLimit: 1024
  # Lolicon APIKEY
  LoliconApiKey: null
  # Yukari APIKEY
  YukariApiKey: null
  # 群组屏蔽设置
  # 数组中的群号不会触发色图功能
  GroupBlock: [ ]

# 动态订阅设置
SubscriptionConfig:
  # 群组订阅设置
  GroupsConfig:
    - GroupId: [ ] # 群号，可以一次设置多个群
      SubscriptionId: [ ] # 订阅的B站用户ID
      LiveSubscriptionId: [ ] # 直播订阅的B站用户ID